[package]
name = "fitcom-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
cpal = "0.18.1"
crossbeam-channel = "0.5.16"
fitcom-net.workspace = true
fitcom-proto.workspace = true
nnnoiseless = "0.5.2"
opus = "0.3.1"
tracing = "0.1.44"
wasapi = "0.23"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_Threading"] }
